server:
  port: 8081

spring:
  application:
    name: pantao
  liquibase:
    change-log: classpath:/db/postgres/changelog-master.xml
    enabled: true
    default-schema: ${DB_SCHEMA:pantao}
  jpa:
    open-in-view: false
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pantao_st_db?currentSchema=pantao}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  logging:
    level:
      liquibase: DEBUG
